### ISSUE TITLE
Official Android dropdown Picker (spinner) onValueChange listener is not called when selecting the same item

### ISSUE THREAD

**Issue by Noitidart** [webschik/react-native-spinner-android#3]
Hi there,
The facebook picker has issues. It doesn't have an event for `onSelect` (without change of value) it is only `onChange`. Also it is not possible to get an event `willShow`, when the dropdown is initially pressed, and before the spinner values show. I was wondering if you would be able to help add these? I was trying but was getting stuck, I'm not a java guy, just js. I was looking at these three files:

* https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/views/picker/events/PickerItemSelectEvent.java
* https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/views/picker/ReactPicker.java
* https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/views/picker/ReactPickerManager.java

May you please give me some tips on where to add what to get a `onClick` /`onSelect` and a `willShow` event please.

**Comment by Noitidart** [comment]
One of the major bug is, if the label of one of the `<Picker.Item>`s changes, it triggers `onValueChange` with the first `<Picker.Item>` value. Very bad bug. I filed a bug for this here - https://github.com/facebook/react-native/issues/16849

**Comment by Noitidart** [comment]
I'm trying to do this Stackover solution - https://stackoverflow.com/a/31743733/1828637 - but I can't figure it out :(

**Comment by Noitidart** [comment]
In summary what I am trying to achieve:

* trigger willShow event before menu shows (onPress of dropdown arrow)
* get onSelect to work (so it fires even if same item selected)
* dont trigger onValueChange on label update

It would be so awesome if you could help me with this, I am learning java in reverse :D by implementing what i need in react-native js side :)

**Comment by webschik** [comment]
Hi @Noitidart , this module is not related to the ReactNative [Picker Component](https://facebook.github.io/react-native/docs/picker.html).
I've created this module when RN didn't have its own dropdown/
